.PHONY: start stop restart status start-with-demo-data seed-demo-data

start:
	./start.sh

stop:
	./stop.sh

restart:
	./restart.sh

status:
	./status.sh

start-with-demo-data:
	./start-with-demo-data.sh

seed-demo-data:
	./seed-demo-data.sh
